#version:  '3'

services:
  juiceshop:
    container_name: juiceshop
    image: bkimminich/juice-shop:latest
    #build:
    #  dockerfile: Dockerfile
    #  context: ./juice-shop
    ports:
        - '3000:3000'

  cloudguard-waf:
        container_name: cp-waf
        image: checkpoint/cloudguard-appsec-standalone:latest
        entrypoint: /cloudguard-appsec-standalone --token $TOKEN --ignore-all
        ports:
           - '80:80'
           - '8500:8500' 
        volumes:
          - ./cp-waf/data:/etc/cp/data
          - ./cp-waf/conf:/etc/cp/conf
          - ./cp-waf/log:/var/log/nano_agent
          - ./cp-waf/etc/nginx/conf.d:/etc/nginx/conf.d
          - ./cp-waf/etc/certs:/etc/certs
          - ./cp-waf/log/nginx:/var/log/nginx

  test-host:
    container_name: cp-tester
    image: cp-waf-demo-test-host
    stdin_open: true
    tty: true
    build:
       dockerfile: Dockerfile
       context: ./tester
    volumes:
      - ./tester/data:/home/web-scraper/data
    hostname: tester

  vampi:
    image: erev0s/vampi:latest
    container_name: vampi 
    ports: 
      - '5000:5000'
    hostname: vampi
    environment:
      - vulnerable=1
      - tokentimetolive=3600
