version:  '3'

services:
  juice-shop:
    image: bkimminich/juice-shop
    #build:
    #  dockerfile: Dockerfile
    #  context: ./juice-shop
    ports:
        - '3000:3000'

  nginx-reverse-proxy:
    container_name: cp-appsec-nginx-reverse-proxy
    build:
      dockerfile: Dockerfile
      context: ./nginx-reverse-proxy
      args:
        NGINX_SERVER_FQDN: 
    ports:
      - '80:80'
      - '8500:8500' 
    ipc: shareable
    #image: checkpoint/infinity-next-nginx
    volumes:
      - ./nginx-reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf 
      - ./nginx-reverse-proxy/log:/var/log/nginx    
    

  agent-container:
    container_name: cp-appsec-agent-container
    # ipc: "container:cp-appsec-nginx-reverse-proxy"  - Changed to support docker-compose ver 1.27+
    ipc: service:nginx-reverse-proxy

    volumes:
      - ./agent-container/data:/etc/cp/data
      - ./agent-container/conf:/etc/cp/conf
      - ./agent-container/logs:/var/log/nano_agent
    #build:
    #  dockerfile: Dockerfile
    #context: ./agent-container
    #image: checkpoint/infinity-next-nano-agent:412743    
    image: checkpoint/infinity-next-nano-agent
    depends_on:
      - nginx-reverse-proxy
    command: ["/cp-nano-agent", "--token", "$TOKEN"]
    hostname: appsec-lab

  test-host:
    container_name: cp-appsec-tester
    stdin_open: true
    tty: true
    build:
       dockerfile: Dockerfile
       context: ./tester
    volumes:
      - ./tester/data:/home/web-scraper/data
    hostname: tester


  vampi:
    image: erev0s/vampi
    container_name: vampi 
    ports: 
      - '5000:5000'
    hostname: vampi
    environment:
      - vulnerable=1
      - tokentimetolive=3600

